# Generated by Django 5.1.7 on 2025-04-15 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groomingdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dom', models.DateField(verbose_name='Date of Manufacturing')),
                ('doe', models.DateField(verbose_name='Date of Expiry')),
                ('suitablefor', models.CharField(choices=[('New born', 'New born'), ('Young', 'Young'), ('Adult', 'Adult'), ('All age', 'All age')], max_length=50)),
                ('foodpreference', models.CharField(choices=[('Non vegetarian', 'Non vegetarian'), ('Vegetarian', 'Vegetarian')], max_length=50)),
                ('flavour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
