# Generated by Django 4.2.20 on 2025-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
