# Generated by Django 5.2 on 2025-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='fees',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerdetails',
            name='fees',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
