# Generated by Django 5.2 on 2025-04-21 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doctordetails_fees_trainerdetails_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('fees', models.CharField(max_length=200)),
                ('paymentId', models.CharField(max_length=200)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctordetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
