# Generated by Django 5.2 on 2025-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_doctorbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomingdetails',
            name='photo',
            field=models.ImageField(null=True, upload_to='grooming_photos/'),
        ),
    ]
