# Generated by Django 5.2 on 2025-04-22 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_groomingdetails_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='petPhoto/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petlist')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vaccineData/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='api.petdata')),
            ],
        ),
    ]
