# Generated by Django 5.2 on 2025-04-23 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_petdata_vaccinedata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='serviceCenter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=100)),
                ('serviceCenter', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=10)),
                ('groomingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groomingdetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=100)),
                ('serviceCenter', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=10)),
                ('trainerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainerdetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
