# Generated by Django 5.2 on 2025-04-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_doctorbooking_date_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paymentid',
        ),
        migrations.AddField(
            model_name='cart',
            name='itemname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
