# Generated by Django 5.2 on 2025-04-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='medicine_name',
            new_name='item_name',
        ),
    ]
