# Generated by Django 5.2 on 2025-04-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_medicine_name_order_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='itemname',
            new_name='itemcategory',
        ),
    ]
