# Generated by Django 5.2 on 2025-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_itemname_cart_itemcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='itemcategory',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
