# Generated by Django 5.2 on 2025-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_userid_order_user_remove_order_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceimage',
            field=models.ImageField(null=True, upload_to='service_photos/'),
        ),
    ]
