# Generated by Django 5.2 on 2025-04-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_service_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlist',
            name='petimage',
            field=models.ImageField(null=True, upload_to='pet_photos/'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='itemimage',
            field=models.ImageField(null=True, upload_to='item_photos/'),
        ),
    ]
