# Generated by Django 5.2 on 2025-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_petlist_petimage_storeitems_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
