# Generated by Django 5.2 on 2025-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_accessory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='image',
            field=models.ImageField(null=True, upload_to='userPhoto/'),
        ),
    ]
