# Generated by Django 5.2 on 2025-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customerdata_createdat_customerdata_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
