# Generated by Django 5.2 on 2025-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_orderitem_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
