# Generated by Django 5.2 on 2025-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_orderitem_deliverystatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
