# Generated by Django 5.2 on 2025-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_orderitem_orderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.JSONField(null=True),
        ),
    ]
