# Generated by Django 5.2 on 2025-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_orderitem_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
