# Generated by Django 5.2 on 2025-04-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_orderitem_deliverystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='deliverystatus',
        ),
    ]
