# Generated by Django 5.2 on 2025-04-28 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_orderitem_deliverystatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.CharField(default='Ordered', max_length=100),
        ),
        migrations.CreateModel(
            name='customerRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
