# Generated by Django 5.2 on 2025-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_doctorbooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrefund',
            name='orderId',
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='balance',
            field=models.CharField(default='0'),
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='date',
            field=models.CharField(default='0'),
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='service_center',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='amount',
            field=models.CharField(),
        ),
    ]
