# Generated by Django 5.2 on 2025-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_customerrefund_orderid_customerrefund_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrefund',
            name='date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='service_center',
            field=models.CharField(),
        ),
    ]
