# Generated by Django 5.2 on 2025-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_customerrefund_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrefund',
            name='service',
            field=models.CharField(null=True),
        ),
    ]
