import React from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Pagination, Autoplay } from 'swiper/modules'; // Removed Navigation module
import 'swiper/css';
import 'swiper/css/pagination';
import '../Styles/Terms.css';

const termsSlides = [
  {
    title: '1. Acceptance of Terms',
    text: 'By accessing or using AutoLead, you agree to be bound by these Terms of Service and our Privacy Policy. This agreement governs your use of the platform, including all features, functionalities, and services provided. If you do not agree to these terms, you must discontinue using the platform immediately. AutoLead reserves the right to update these terms at any time, and it is your responsibility to review them periodically. Continued use of the platform constitutes acceptance of the updated terms. These terms form a legally binding agreement between you and AutoLead. It is crucial that you understand and accept these obligations before proceeding. Any failure to comply with these terms may result in suspension, termination, or legal action. We encourage users to revisit this section regularly and stay informed about their rights and responsibilities under this agreement.',
  },
  {
    title: '2. User Responsibilities',
    text: 'You are responsible for all activities that occur under your account. This includes ensuring that your login credentials are kept secure and not shared with unauthorized individuals. You agree to use the platform only for lawful purposes and in compliance with all applicable laws and regulations. Any misuse of the platform may result in suspension or termination of your account. Additionally, you are responsible for maintaining the confidentiality of sensitive data and ensuring that your use of the platform does not harm other users or the platform itself. You must immediately report any unauthorized access or breach of security to AutoLead. Failure to act responsibly may not only affect your access to the platform but may also lead to legal consequences, depending on the severity of the misuse or data breach.',
  },
  {
    title: '3. Use Restrictions',
    text: 'You agree not to misuse the platform in any way, including but not limited to attempting to reverse engineer features, disrupt service functionality, or engage in activities that harm the platform or its users. Unauthorized access, data scraping, or any form of exploitation of the platform’s resources is strictly prohibited. Furthermore, you must not use the platform to distribute malicious software, spam, or any content that violates the rights of others. Violations of these restrictions may result in legal action. You also agree not to engage in activities that could compromise the security, integrity, or availability of the platform, such as flooding the network or executing denial-of-service attacks. The platform reserves the right to monitor usage and take appropriate action if suspicious behavior is detected.',
  },
  {
    title: '4. Termination',
    text: 'We reserve the right to suspend or terminate your access to the platform at any time if you violate these terms or engage in suspicious or harmful activities. Termination may occur without prior notice, and you will remain liable for any obligations incurred prior to termination. We also reserve the right to pursue legal action for any damages caused by your actions. Additionally, AutoLead may terminate your account if it detects prolonged inactivity or misuse of the platform’s resources. In cases of severe violation, AutoLead may cooperate with law enforcement authorities and disclose any relevant user data as required by law. Termination of service does not absolve you from liability for actions taken while your account was active, nor does it grant you any entitlement to recover lost data or services.',
  },
  {
    title: '5. Limitation of Liability',
    text: 'To the maximum extent permitted by law, AutoLead is not liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform. This includes, but is not limited to, loss of data, revenue, or business opportunities. You acknowledge that the platform is provided "as is" and "as available," without any warranties of any kind. AutoLead does not guarantee uninterrupted service or error-free functionality and is not responsible for any technical issues that may arise. Users are solely responsible for backing up their data and ensuring compatibility of the platform with their systems. Any reliance on the availability, performance, or results generated by the platform is at your own risk. AutoLead disclaims any liability for third-party content or services integrated with or accessed through the platform.',
  },
  {
    title: '6. Privacy Policy',
    text: 'Your use of the platform is also governed by our Privacy Policy, which outlines how we collect, use, and protect your data. By using the platform, you consent to the practices described in the Privacy Policy. AutoLead is committed to safeguarding your personal information and ensuring compliance with applicable data protection laws. However, you are responsible for ensuring that your use of the platform complies with your local privacy regulations. We do not sell or share your personal data with unauthorized third parties without your consent, except as required by law. Our data handling practices are subject to periodic review and improvement. It is your responsibility to read the Privacy Policy thoroughly and understand how your information will be handled, stored, and used within the scope of our services.',
  },
  {
    title: '7. Intellectual Property',
    text: 'All content, trademarks, and data on this platform are the property of AutoLead or its licensors. Unauthorized use, reproduction, or distribution of this content is strictly prohibited and may result in legal action. You agree not to copy, modify, or create derivative works based on the platform’s content without prior written consent from AutoLead. Any violation of intellectual property rights will be pursued to the fullest extent of the law. This includes but is not limited to logos, UI/UX designs, source code, documentation, and proprietary algorithms. Users must respect the intellectual contributions of AutoLead and avoid any behavior that undermines its proprietary assets or misleads the public into believing there is an association or endorsement by AutoLead where none exists.',
  },
  {
    title: '8. Modifications to the Terms',
    text: 'We reserve the right to modify these Terms of Service at any time. Continued use of the platform constitutes acceptance of the updated terms. It is your responsibility to review the terms periodically for changes. AutoLead will make reasonable efforts to notify users of significant updates, but it is ultimately your responsibility to stay informed about the terms governing your use of the platform. These modifications may include changes to user obligations, platform features, or legal requirements. Major updates may be highlighted through in-app notifications or via registered email. Users who disagree with the revised terms must discontinue use immediately, and failure to do so will be considered implicit acceptance of the new conditions.',
  },
  {
    title: '9. Governing Law',
    text: 'These terms are governed by the laws of your jurisdiction. Any disputes arising from the use of the platform will be resolved in accordance with applicable laws and regulations. By using the platform, you agree to submit to the exclusive jurisdiction of the courts in your region for the resolution of any disputes. AutoLead is not responsible for ensuring compliance with laws outside its operational jurisdiction. If any provision of these terms is found to be unenforceable or invalid under local law, the remaining provisions will continue in full force and effect. The governing law also dictates how conflicts will be interpreted and what remedies are available. Users are advised to seek independent legal counsel if they are uncertain about how these laws apply.',
  },
];

export default function TermsSwiper() {
  return (
    <section className="terms-section">
      <div className="container-fluid">
        <div className="row g-0">
          {/* Left fixed image */}
          <div className="col-md-4 terms-fixed-img" data-aos="fade-right" data-aos-delay="200">
            <img
              src="/assets/img/services-page-title-bg.jpg"
              alt="Visual"
              className="img-fluid full-height-img"
            />
          </div>

          {/* Swiper section */}
          <div className="col-md-8 d-flex align-items-center">
            <div className="container py-5" data-aos="fade-left" data-aos-delay="300">
              <Swiper
                modules={[Pagination, Autoplay]} // Removed Navigation module
                pagination={{ clickable: true }}
                autoplay={{ delay: 5000 }}
                className="terms-swiper"
                spaceBetween={30}
                slidesPerView={1}
                loop={true}
              >
                {termsSlides.map((slide, index) => (
                  <SwiperSlide key={index}>
                    <div className="terms-content" data-aos="fade-up" data-aos-delay="400">
                      <h3 className="terms-title">{slide.title}</h3>
                      <p className="terms-text">{slide.text}</p>
                    </div>
                  </SwiperSlide>
                ))}
              </Swiper>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
